name: First Flow
on: 
  push: 
    branches: 
      - master
jobs: 
  example-job: 
    runs-on: ubuntu-latest 

    steps: 
      - name: Print Welcome
        run: echo "Hello world"

      - name: Checkout 
        uses: actions/checkout@v5.0.0

      - name: List files
        run: ls -la

